# Generated by Django 6.0.6 on 2026-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('size', models.CharField(choices=[('1L', '1 Litre'), ('5L', '5 Litres'), ('10L', '10 Litres'), ('20L', '20 Litres')], max_length=3)),
            ],
        ),
    ]
