# Generated by Django 6.0.6 on 2026-07-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('api', 'API/Sensor')], default='manual', max_length=10)),
            ],
        ),
    ]
