# Generated by Django 6.0.6 on 2026-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_sale_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
