# Generated by Django 6.0.6 on 2026-07-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sale_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
