# Generated by Django 6.0.6 on 2026-07-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_customer_discount_percentage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date'], name='shop_sale_date_280cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_paid', 'is_cancelled'], name='shop_sale_is_paid_0223e8_idx'),
        ),
    ]
