# Generated by Django 6.0.6 on 2026-08-13 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_sale_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +254XXXXXXXXX or 254XXXXXXXXX', regex='^\\+?254\\d{9}$')]),
        ),
    ]
